image: Visual Studio 2019

before_build:  
- ps: dotnet restore -v d
 
configuration: Release

build:
  verbosity: minimal

test:
  assemblies:
    - '**\*.tests.dll'
  cmd: nunit3-console --result=myresults.xml;format=AppVeyor